# docker build -f Dockerfile.13.17.1 -t astbss/asterisk:13.17.1 .
# docker run -it --name asterisk --rm astbss/asterisk:13.17.1
# docker run -it --rm astbss/asterisk:13.17.1

FROM astbss/asterisk:13.17.1-src
LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

FROM php:7.2-cli
LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
   

WORKDIR /usr/src
COPY --from=0 /usr/src .

ENV ASTERISK_VERSION 13.17.1
WORKDIR /usr/src/asterisk-${ASTERISK_VERSION}

RUN apt-get update \
    && apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
    wget nano  bash-completion sqlite3 libjansson4 openssh-server \
    && apt-get clean && apt-get --yes --quiet autoremove --purge \
    && rm -rf  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            /usr/share/doc/* /usr/share/groff/* /usr/share/info/* /usr/share/linda/* \
            /usr/share/lintian/* /usr/share/locale/* /usr/share/man/*


# Update max number of open files. 
# Set tty
RUN make install \
    && rm -r /usr/src/* \
    && sed -i -e 's/# MAXFILES=/MAXFILES=/' /usr/sbin/safe_asterisk \
    && sed -i 's/TTY=9/TTY=/g' /usr/sbin/safe_asterisk

WORKDIR /usr/src

# CMD asterisk -fvvv
# CMD /usr/sbin/safe_asterisk
# CMD /bin/bash
CMD asterisk -fvvv

# ENV PATH=bin:vendor/bin:$PATH
# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# ENTRYPOINT ["/usr/sbin/safe_asterisk"]

