# docker build -f Dockerfile.php7.2-alpine3.8 -t astbss/php:7.2-alpine3.8 .
# docker run -it --rm astbss/php:7.2-alpine3.8

FROM php:7.2-alpine3.8

LABEL maintainer="are@astbss.com"

# system setup subversion
RUN apk add --no-cache subversion bash \
    && echo "I am done!!!"
    
# VOLUME /usr/lib/asterisk/sounds /var/lib/asterisk/keys /var/lib/asterisk/phoneprov /var/spool/asterisk /var/log/asterisk

# ADD docker-entrypoint.sh /docker-entrypoint.sh

# ENTRYPOINT ["/docker-entrypoint.sh"]
 