# docker build -f Dockerfile.13.24.1 -t astbss/asterisk:13.24.1 .
# docker run -it --name asterisk --rm astbss/asterisk:13.24.1
# docker run -it --rm astbss/asterisk:13.24.1


# vim:set ft=dockerfile:
FROM debian:stretch-slim

LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# 13.24.1

ENV ASTERISK_VERSION 13-current
ENV OPUS_CODEC       asterisk-13.0/x86-64/codec_opus-13.0_current-x86_64

COPY build-asterisk.sh /
RUN /build-asterisk.sh
RUN mkdir -p /etc/asterisk

EXPOSE 5060/udp 5060/tcp
VOLUME /var/lib/asterisk/sounds /var/lib/asterisk/keys /var/lib/asterisk/phoneprov /var/spool/asterisk /var/log/asterisk

COPY debian-9/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/sbin/asterisk", "-vvvdddf", "-T", "-W", "-U", "asterisk", "-p"]

