# docker build -f Dockerfile.php7.2-asterisk-13.17.1 -t astbss/asterisk:13.17.1-php7.2.30 .
# docker push astbss/asterisk:13.17.1-php7.2.30

# docker run -it --name asterisk --rm astbss/asterisk:13.17.1-php7.2.30
# docker run -it --rm astbss/asterisk:13.17.1-php7.2.30 bash

# php7.2.14 Digest: astbss/asterisk@sha256:68605f14a1280670dd0947593ac091c1b79bbfcb87c6e746825b4ebe865c8f75
# php7.2.30 Digest: astbss/asterisk@sha256:47186e8b0a7d4be9f800bf08ccbe06371e39e90d1775a7adc03541f3b528e947

# vim:set ft=dockerfile:
# FROM debian:stretch-slim

FROM php:7.2.30-cli-buster
LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN docker-php-ext-install mysqli pdo pdo_mysql




ENV ASTERISK_VERSION 16.9.0
ENV OPUS_CODEC       asterisk-16.0/x86-64/codec_opus-16.0_current-x86_64

COPY build-asterisk16.sh /
RUN /build-asterisk16.sh

RUN mkdir -p /etc/asterisk \
    && rm -f /etc/odbc.ini \
    && ln -s /etc/asterisk/odbc.ini /etc/odbc.ini \
    && ln /usr/local/bin/php /usr/bin/php


# unixodbc unixodbc-dev odbcinst
ADD debian-9/odbcinst.ini /etc/odbcinst.ini
ADD debian-9/libmaodbc.so /usr/lib/x86_64-linux-gnu/odbc/libmaodbc.so
ADD debian-9/resolv.conf /var/astbss/resolv2.conf
# isql -v astbss # Test odbc


# Development and Debug only
# openvpn vtun fail2ban netcat-openbsd = nc
RUN apt-get update \
    && apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
      wget curl nano iptables procps \
      net-tools iproute2 iputils-ping netcat-openbsd ngrep \


WORKDIR /app
# CMD ["/usr/sbin/asterisk", "-vvvdddfp"]
CMD ["bash"]
