# vim:set ft=dockerfile:
# docker build -f Dockerfile.python3.7 -t astbss/python:3.7 .
# docker run -it --rm astbss/python:3.7 bash

# https://hub.docker.com/_/python

# FROM debian:stretch-slim

FROM python:3.7.2-slim-stretch
LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt-get update \
    && apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
    git nano wget curl net-tools iproute2 iputils-ping \
    && apt-get clean && apt-get --yes --quiet autoremove --purge \
    && rm -rf  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            /usr/share/doc/* /usr/share/groff/* /usr/share/info/* /usr/share/linda/* \
            /usr/share/lintian/* /usr/share/locale/* /usr/share/man/*


# ENTRYPOINT ["docker-php-entrypoint"]

WORKDIR /home
# EXPOSE 8088
# CMD ["apache2-foreground"]
