#!/bin/bash

# sudo wget https://raw.githubusercontent.com/astbss/astbss/master/Kubernetes/kex -O /usr/local/bin/kex ; sudo chmod +x /usr/local/bin/kex

# https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-autocomplete
# Enable kubernetes completion via adding this to your ~/.bashrc
# alias k=kubectl
# source <(kubectl completion bash)
# complete -F __start_kubectl k

# https://kubernetes.io/docs/reference/kubectl/cheatsheet/
# https://gist.github.com/tamas-molnar/32a07c0eb83e95484e3cdb4b7fada32b
# https://www.sfgroups.com/kubernetes/kubectl_bash_alias/
# https://itnext.io/kubernetes-command-line-tools-acad11683794


# set -xv
# set -ex
# set -e stops the execution of a script if a command or pipeline has an error
# set -v Echoes all commands before executing
# set -x 	Similar to -v, but expands commands
# https://www.tldp.org/LDP/abs/html/options.html

# Simple Login to Pod Bash Script
# cp kex /usr/local/bin/kex

P="$1"
D=""

case $P in
  (n|node|nodes)
    echo "kubectl get nodes"
    kubectl get nodes
    exit
  ;; # OK
esac

# https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/
case $P in
  (c|container|containers)
    kubectl get pods -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers [*]}{.name}{", "}{end}{end}'
    exit
  ;; # OK
esac

case $P in
  (p|pod|pods)
    kubectl get pods
    exit
  ;; # OK
esac

case $P in
  (Save|save)
    D=$(kubectl get pods | grep ibix-$2 | cut -f1 -d' ')
    echo "Pod Name: $D"
    echo "kubectl exec -it $D -c ibix-asterisk -- /usr/local/astpbx-git/scripts/astpbxsettings.php"
    kubectl exec -it $D -c ibix-asterisk -- /usr/local/astpbx-git/scripts/astpbxsettings.php
    exit
  ;; # OK
esac

case $P in
  (Delete|delete)
    D=$(kubectl get pods | grep $2 | cut -f1 -d' ')
    echo "kubectl delete pod $D"
    kubectl delete pod $D
    sleep 0.1
    kubectl get pods -o=wide    
    exit
  ;; # OK
esac

case $P in
  (dep|depl|deployment|deployments)
    echo "kubectl get deployments"
    kubectl get deployments
    exit
  ;; # OK
esac

case $P in
  (serv|service|services)
    echo "kubectl get services"
    kubectl get services
    exit
  ;; # OK
esac

case $P in
  (secret|secrets)
    echo "kubectl get secrets"
    kubectl get secrets
    exit
  ;; # OK
esac

case $P in
  (h|H|Help|help)
    echo "Usage: kex COMMAND [ARGS]... "
    echo ""
    echo "help  Show this message and exit."
    echo ""
    echo "Commands:"
    echo "  containers|c  get pods and all container names"
    echo "  pods|p        kubectl get pods"
    echo "  nodes|n       kubectl get nodes"
    echo "  dep           kubectl get deployments"
    echo "  deployments   kubectl get deployments"

    echo "  services|serv kubectl get services"
    echo "  secrets       kubectl get secrets"

    echo "  [pod] delete  kubectl delete pod"
    echo "  Save [pbx|pod]"
    exit
  ;; # OK
esac

# -n True if the length of string is non-zero
if [ -n "$P" ] ; then
  D=$(kubectl get pods | grep $P | cut -f1 -d' ')
else
  echo "kubectl get pods -o=wide"
  kubectl get pods -o=wide
  exit  
fi

echo "Pod Name: $D"

if [ "$2"  == "delete" ] ; then
    echo "kubectl delete pod $D"
    kubectl delete pod $D
    sleep 0.1
    kubectl get pods -o=wide
elif [ -n "$2" ] ; then
  kubectl exec  "$D" -it --container $2 -- bash -il
else
  kubectl exec  "$D" -it -- bash -il
fi
