# kubectl apply -f https://raw.githubusercontent.com/astbss/astbss/master/Kubernetes/nginx-recreate.yaml
# kubectl apply -f https://raw.githubusercontent.com/astbss/astbss/master/Kubernetes/nginx-replicas-3.yaml
# kubectl apply -f https://raw.githubusercontent.com/astbss/astbss/master/Kubernetes/networkpod.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-replicas-3
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
