# kubectl exec -it powershell --container powershell -- bash
# kubectl exec -it powershell -- pwsh

apiVersion: v1
kind: Pod
metadata:
  name: powershell
spec:
  containers:
  - name: powershell
    # command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    # command: ["pwsh", "-c", "sleep 3600"]
    command: ["pwsh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: mcr.microsoft.com/powershell:latest
