# kubectl exec -it powershell --container powershell -- bash
# kubectl exec -it powershell -- pwsh

apiVersion: v1
kind: Pod
metadata:
  name: powershell
spec:
  containers:
  - name: powershell
    command: ["pwsh", "-c", "while ($true) { Start-Sleep -Seconds 1 }"]
    image: mcr.microsoft.com/powershell:latest
