apiVersion: v1
kind: Service
metadata:
  name: tcp-echo
  namespace: default
spec:
  type: NodePort
  selector:
    app: tcp-echo
  ports:
  - name: tcp-echo
    protocol: TCP
    port: 446
    targetPort: 446
    nodePort: 30446

# kubectl get service -o=wide
    