# kubectl apply -f https://raw.githubusercontent.com/astbss/astbss/master/Kubernetes/tcp-echo-pod.yaml
# kubectl apply -f tcp-echo-pod.yaml
# kubectl get pods
# kubectl delete pod tcp-echo
# kubectl exec -it tcp-echo --container networkpod -- bash
# kubectl exec -it tcp-echo -- bash

apiVersion: v1
kind: Pod
metadata:
  name: tcp-echo
  labels:
    app: tcp-echo
spec:
  containers:
  - image: maniankara/tcp-echo:1.0
    ports:
    - containerPort: 446
      hostPort: 446
    name: tcp-echo-server
    args: ["--port", "446"]
---

#   hostNetwork: true

# nc 10.244.0.27 446  
# nc 10.101.110.80 446
