# vim:set ft=dockerfile:
# docker build -f Dockerfile.python3.7.2 -t astbss/python:3.7.2 .
# docker tag astbss/python:3.7.2 astbss/python:latest
# docker push astbss/python:3.7.2 ; docker push astbss/python:latest
# docker run -it --rm astbss/python:3.7.2 bash
# docker run -v /app/my-app:/app -it  --rm --entrypoint "/bin/bash" astbss/python:3.7.2
# docker run -v /home/are:/app -it --rm astbss/python:3.7.2 bash

# https://hub.docker.com/_/python

# FROM debian:stretch-slim

FROM python:3.7.2-slim-stretch
LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt-get update \
    && apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
    git nano wget curl net-tools iproute2 iputils-ping openssh-client \
    && apt-get clean && apt-get --yes --quiet autoremove --purge \
    && mkdir -p /root/.ssh && mkdir -p /home/are/.ssh \
    && rm -rf  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            /usr/share/doc/* /usr/share/groff/* /usr/share/info/* /usr/share/linda/* \
            /usr/share/lintian/* /usr/share/locale/* /usr/share/man/*

# Create app directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/

RUN pip install -r /app/requirements.txt \
  && pip3 install ansible \ 
  && pip install confluent-kafka \
  && mkdir -p /root/keys && mkdir -p /root/test && mkdir -p /root/app 

# ansible-2.7.10

# ENTRYPOINT ["/bin/bash", "/app/gunicorn.sh"]
# ENTRYPOINT ["/bin/bash"]

# EXPOSE 8088
# CMD ["gunicorn", "-w 4", "main:app"]

CMD ["bash"]
