# vim:set ft=dockerfile:
# https://www.docker.com/blog/containerized-python-development-part-1/

# docker build -f Dockerfile.init3.7 -t astbss/python:init3.7 .
# docker push astbss/python:init3.7
# docker run -it --rm astbss/python:init3.7 bash

# Get sha256 using docker inspect RepoDigests: docker inspect
# docker run -v /app/my-app:/app -it  --rm --entrypoint "/bin/bash" astbss/python:3.7.6
# docker run -v /home/are:/app -it --rm astbss/python:3.7.6 bash

# https://hub.docker.com/_/python

# FROM debian:stretch-slim

# set base image (host OS)
FROM python:3.7-buster AS builder
# FROM python:3.7-slim

# Install dependencies
COPY requirements.txt /requirements.txt

# install dependencies to the local user directory (eg. /root/.local)
RUN pip install --user -r requirements.txt


# second unnamed stage
FROM python:3.7-slim-buster
WORKDIR /code

LABEL maintainer="are@astbss.com"
ENV DEBIAN_FRONTEND noninteractive

# At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# copy only the dependencies installation from the 1st stage image
COPY --from=builder /root/.local/bin /root/.local
COPY ./src .

# apt-get -y install freetds-dev   # FreeTDS is required for pymssql
#RUN apt-get update \
#    && apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
#    git nano wget curl net-tools iproute2 iputils-ping openssh-client vim \
#    gcc python3-dev libssl-dev libkrb5-dev freetds-dev gss-ntlmssp g++ unixodbc-dev\
#    && apt-get clean && apt-get --yes --quiet autoremove --purge \
#    && rm -rf  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
#            /usr/share/doc/* /usr/share/groff/* /usr/share/info/* /usr/share/linda/* \
#            /usr/share/lintian/* /usr/share/locale/* /usr/share/man/*




#RUN pip install --upgrade pip \
#  && pip install -r /requirements.txt \


# docker run -it --rm python:3.7-buster bash
# docker images
# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 20.1.1
ENV PYTHON_VERSION 3.7.8
# ENV PYTHONPATH=/usr/local/lib/python3.7/site-packages:/usr/local/lib/python3.7

# update PATH environment variable
ENV PATH=/root/.local:$PATH

# ansible 2.8.2

# ENTRYPOINT ["/bin/bash", "/app/gunicorn.sh"]
# ENTRYPOINT ["/bin/bash"]

# EXPOSE 8088
# CMD ["gunicorn", "-w 4", "main:app"]

# CMD ["bash"]
CMD ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
